export default {
    benefit1: require('../assets/images/account-benefits-1.png'),
    benefit2: require('../assets/images/account-benefits-2.png'),
    benefit3: require('../assets/images/account-benefits-3.png'),
    depositImage: require('../assets/images/deposit.png'),
    withdrawImage: require('../assets/images/withdraw.png'),
    withdrawRequestImage: require('../assets/images/withdrawal.png'),
    paymentImage: require('../assets/images/payment.png'),
    refundImage: require('../assets/images/refund.png'),
    logoImage: require('../assets/logo/pah-logo.png'),
    cartImage: require('../assets/images/cart.png'),
    searchImage: require('../assets/images/search.png'),
    orderSuccessImage: require('../assets/images/order-success.png'),
    warningImage: require('../assets/images/warning.png'),
    successImage: require('../assets/images/success.png'),
    failedImage: require('../assets/images/failed.png'),
    orderFailImage: require('../assets/images/order-failed.png'),
    walletImage: require('../assets/images/wallet.png'), 
    checkMailImage: require('../assets/images/emailverify.png'), 
    resetPasswordImage: require('../assets/images/reset-password.png'), 
    changePasswordImage: require('../assets/images/changepassword.png'), 
    alertImage: require('../assets/images/alert.png'), 
    pendingImage: require('../assets/images/hourglass.png'), 
    doneImage: require('../assets/images/check.png'), 
    rejectImage: require('../assets/images/decline.png'), 
    infoImage: require('../assets/images/alert1.png'), 
    defaultAvatar: 'https://static.vecteezy.com/system/resources/thumbnails/001/840/618/small/picture-profile-icon-male-icon-human-or-people-sign-and-symbol-free-vector.jpg'
}